#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ESP_IRIS_PROTOCOL_VERSION 1U
#define ESP_IRIS_WIRE_HEADER_SIZE 32U
#define ESP_IRIS_MAX_PAYLOAD_SIZE 4000U
#define ESP_IRIS_MAX_WIRE_FRAME_SIZE 4096U

typedef enum {
    ESP_IRIS_CHANNEL_CONTROL = 0,
    ESP_IRIS_CHANNEL_LOG = 1,
    ESP_IRIS_CHANNEL_EVENT = 2,
    ESP_IRIS_CHANNEL_SCREEN = 3,
    ESP_IRIS_CHANNEL_IMAGE = 4,
    ESP_IRIS_CHANNEL_AUDIO = 5,
    ESP_IRIS_CHANNEL_OTA = 6,
    ESP_IRIS_CHANNEL_CRASH = 7,
    ESP_IRIS_CHANNEL_FILE = 8,
    ESP_IRIS_CHANNEL_SYSTEM_UPDATE = 9,
    ESP_IRIS_CHANNEL_COUNT,
} esp_iris_channel_t;

typedef enum {
    ESP_IRIS_CONTROL_HELLO = 0x01,
    ESP_IRIS_CONTROL_HELLO_ACK = 0x02,
    ESP_IRIS_CONTROL_PING = 0x03,
    ESP_IRIS_CONTROL_PONG = 0x04,
    ESP_IRIS_CONTROL_TIME_SYNC_REQUEST = 0x05,
    ESP_IRIS_CONTROL_TIME_SYNC_RESPONSE = 0x06,
    ESP_IRIS_CONTROL_STATUS_REQUEST = 0x07,
    ESP_IRIS_CONTROL_STATUS_RESPONSE = 0x08,
    ESP_IRIS_CONTROL_CREDIT = 0x09,
    ESP_IRIS_CONTROL_REQUEST = 0x10,
    ESP_IRIS_CONTROL_RESPONSE = 0x11,
    ESP_IRIS_CONTROL_CANCEL = 0x12,
    ESP_IRIS_CONTROL_JOB_QUERY = 0x13,
    ESP_IRIS_CONTROL_JOB_STATUS = 0x14,
    ESP_IRIS_CONTROL_RESTART = 0x15,
    ESP_IRIS_CONTROL_AUTH_RESULT = 0x16,
    ESP_IRIS_CONTROL_ERROR = 0x7f,
} esp_iris_control_type_t;

typedef enum {
    ESP_IRIS_LOG_RECORD = 0x01,
} esp_iris_log_type_t;

typedef enum {
    ESP_IRIS_CRASH_METADATA_REQUEST = 0x01,
    ESP_IRIS_CRASH_METADATA_RESPONSE = 0x02,
    ESP_IRIS_CRASH_READ_REQUEST = 0x03,
    ESP_IRIS_CRASH_READ_RESPONSE = 0x04,
} esp_iris_crash_type_t;

typedef enum {
    ESP_IRIS_MEDIA_OPEN = 0x01,
    ESP_IRIS_MEDIA_OPENED = 0x02,
    ESP_IRIS_MEDIA_READ = 0x03,
    ESP_IRIS_MEDIA_DATA = 0x04,
    ESP_IRIS_MEDIA_CLOSE = 0x05,
    ESP_IRIS_MEDIA_MIRROR_START = 0x06,
    ESP_IRIS_MEDIA_MIRROR_STOP = 0x07,
    ESP_IRIS_MEDIA_MIRROR_STATE = 0x08,
} esp_iris_media_type_t;

typedef enum {
    ESP_IRIS_OTA_BEGIN = 0x01,
    ESP_IRIS_OTA_BEGIN_RESPONSE = 0x02,
    ESP_IRIS_OTA_DATA = 0x03,
    ESP_IRIS_OTA_DATA_RESPONSE = 0x04,
    ESP_IRIS_OTA_END = 0x05,
    ESP_IRIS_OTA_END_RESPONSE = 0x06,
    ESP_IRIS_OTA_CANCEL = 0x07,
    ESP_IRIS_OTA_STATUS = 0x08,
} esp_iris_ota_type_t;

typedef enum {
    ESP_IRIS_SYSTEM_UPDATE_BEGIN = 0x01,
    ESP_IRIS_SYSTEM_UPDATE_BEGIN_RESPONSE = 0x02,
    ESP_IRIS_SYSTEM_UPDATE_COMPONENT_BEGIN = 0x03,
    ESP_IRIS_SYSTEM_UPDATE_COMPONENT_BEGIN_RESPONSE = 0x04,
    ESP_IRIS_SYSTEM_UPDATE_DATA = 0x05,
    ESP_IRIS_SYSTEM_UPDATE_DATA_RESPONSE = 0x06,
    ESP_IRIS_SYSTEM_UPDATE_COMPONENT_END = 0x07,
    ESP_IRIS_SYSTEM_UPDATE_COMPONENT_END_RESPONSE = 0x08,
    ESP_IRIS_SYSTEM_UPDATE_COMMIT = 0x09,
    ESP_IRIS_SYSTEM_UPDATE_COMMIT_RESPONSE = 0x0a,
    ESP_IRIS_SYSTEM_UPDATE_CANCEL = 0x0b,
    ESP_IRIS_SYSTEM_UPDATE_STATUS = 0x0c,
    ESP_IRIS_SYSTEM_UPDATE_STATUS_RESPONSE = 0x0d,
    ESP_IRIS_SYSTEM_UPDATE_INVENTORY = 0x0e,
    ESP_IRIS_SYSTEM_UPDATE_INVENTORY_RESPONSE = 0x0f,
} esp_iris_system_update_type_t;

typedef enum {
    ESP_IRIS_FILE_VOLUMES_REQUEST = 0x01,
    ESP_IRIS_FILE_VOLUMES_RESPONSE = 0x02,
    ESP_IRIS_FILE_STAT_REQUEST = 0x03,
    ESP_IRIS_FILE_STAT_RESPONSE = 0x04,
    ESP_IRIS_FILE_LIST_OPEN = 0x05,
    ESP_IRIS_FILE_LIST_OPENED = 0x06,
    ESP_IRIS_FILE_LIST_NEXT = 0x07,
    ESP_IRIS_FILE_LIST_DATA = 0x08,
    ESP_IRIS_FILE_CLOSE = 0x09,
    ESP_IRIS_FILE_CLOSE_RESPONSE = 0x0a,
    ESP_IRIS_FILE_READ_OPEN = 0x0b,
    ESP_IRIS_FILE_READ_OPENED = 0x0c,
    ESP_IRIS_FILE_READ = 0x0d,
    ESP_IRIS_FILE_DATA = 0x0e,
    ESP_IRIS_FILE_WRITE_OPEN = 0x0f,
    ESP_IRIS_FILE_WRITE_OPENED = 0x10,
    ESP_IRIS_FILE_WRITE = 0x11,
    ESP_IRIS_FILE_WRITE_ACK = 0x12,
    ESP_IRIS_FILE_COMMIT = 0x13,
    ESP_IRIS_FILE_COMMIT_RESPONSE = 0x14,
    ESP_IRIS_FILE_ABORT = 0x15,
    ESP_IRIS_FILE_ABORT_RESPONSE = 0x16,
    ESP_IRIS_FILE_MKDIR = 0x17,
    ESP_IRIS_FILE_MKDIR_RESPONSE = 0x18,
    ESP_IRIS_FILE_DELETE = 0x19,
    ESP_IRIS_FILE_DELETE_RESPONSE = 0x1a,
    ESP_IRIS_FILE_RENAME = 0x1b,
    ESP_IRIS_FILE_RENAME_RESPONSE = 0x1c,
    ESP_IRIS_FILE_WRITE_STATUS = 0x1d,
    ESP_IRIS_FILE_WRITE_STATUS_RESPONSE = 0x1e,
} esp_iris_file_type_t;

typedef enum {
    ESP_IRIS_FILE_STATUS_OK = 0,
    ESP_IRIS_FILE_STATUS_INVALID_ARGUMENT = 1,
    ESP_IRIS_FILE_STATUS_NOT_FOUND = 2,
    ESP_IRIS_FILE_STATUS_NOT_DIRECTORY = 3,
    ESP_IRIS_FILE_STATUS_NOT_FILE = 4,
    ESP_IRIS_FILE_STATUS_READ_ONLY = 5,
    ESP_IRIS_FILE_STATUS_BUSY = 6,
    ESP_IRIS_FILE_STATUS_NO_MEMORY = 7,
    ESP_IRIS_FILE_STATUS_IO = 8,
    ESP_IRIS_FILE_STATUS_NOT_SUPPORTED = 9,
    ESP_IRIS_FILE_STATUS_CONFLICT = 10,
    ESP_IRIS_FILE_STATUS_EXISTS = 11,
    ESP_IRIS_FILE_STATUS_NOT_EMPTY = 12,
    ESP_IRIS_FILE_STATUS_NO_SPACE = 13,
    ESP_IRIS_FILE_STATUS_HASH_MISMATCH = 14,
} esp_iris_file_status_t;

enum {
    ESP_IRIS_FILE_VOLUME_READ = 1U << 0,
    ESP_IRIS_FILE_VOLUME_LIST = 1U << 1,
    ESP_IRIS_FILE_VOLUME_MTIME = 1U << 2,
    ESP_IRIS_FILE_VOLUME_WRITE = 1U << 3,
    ESP_IRIS_FILE_VOLUME_DELETE = 1U << 4,
    ESP_IRIS_FILE_VOLUME_MKDIR = 1U << 5,
    ESP_IRIS_FILE_VOLUME_RENAME = 1U << 6,
    ESP_IRIS_FILE_VOLUME_ATOMIC_REPLACE = 1U << 7,
    ESP_IRIS_FILE_VOLUME_HASH = 1U << 8,
};

enum {
    ESP_IRIS_FILE_WRITE_OVERWRITE = 1U << 0,
    ESP_IRIS_FILE_WRITE_IF_MATCH = 1U << 1,
};

typedef enum {
    ESP_IRIS_FILE_KIND_REGULAR = 1,
    ESP_IRIS_FILE_KIND_DIRECTORY = 2,
} esp_iris_file_kind_t;

typedef enum {
    ESP_IRIS_EVENT_BOOT = 0x01,
    ESP_IRIS_EVENT_HEALTHY = 0x03,
    ESP_IRIS_EVENT_PLANNED_RESTART = 0x04,
    ESP_IRIS_EVENT_LINK_READY = 0x05,
    ESP_IRIS_EVENT_PREVIOUS_BOOT_CRASH = 0x06,
    ESP_IRIS_EVENT_RECOVERY_ENTERED = 0x07,
    ESP_IRIS_EVENT_CORE_DUMP_AVAILABLE = 0x08,
    ESP_IRIS_EVENT_JOB_UPDATE = 0x20,
    ESP_IRIS_EVENT_OTA_READY = 0x21,
} esp_iris_event_type_t;

enum {
    ESP_IRIS_FLAG_RESPONSE = 1U << 0,
    ESP_IRIS_FLAG_ERROR = 1U << 1,
    ESP_IRIS_FLAG_RELIABLE = 1U << 2,
    ESP_IRIS_FLAG_STREAM_BEGIN = 1U << 3,
    ESP_IRIS_FLAG_STREAM_END = 1U << 4,
};

enum {
    ESP_IRIS_CAP_LOG = 1ULL << 0,
    ESP_IRIS_CAP_EVENT = 1ULL << 1,
    ESP_IRIS_CAP_STATUS = 1ULL << 2,
    ESP_IRIS_CAP_TIME_SYNC = 1ULL << 3,
    ESP_IRIS_CAP_SCREEN = 1ULL << 4,
    ESP_IRIS_CAP_OTA = 1ULL << 5,
    ESP_IRIS_CAP_CRASH = 1ULL << 6,
    ESP_IRIS_CAP_AUTH = 1ULL << 7,
    ESP_IRIS_CAP_RPC = 1ULL << 8,
    ESP_IRIS_CAP_JOBS = 1ULL << 9,
    ESP_IRIS_CAP_IMAGE = 1ULL << 10,
    ESP_IRIS_CAP_AUDIO = 1ULL << 11,
    ESP_IRIS_CAP_MIRROR = 1ULL << 12,
    ESP_IRIS_CAP_FILE = 1ULL << 13,
    ESP_IRIS_CAP_OTA_PROJECT_NAME_MATCH = 1ULL << 14,
    ESP_IRIS_CAP_SYSTEM_UPDATE = 1ULL << 15,
    ESP_IRIS_CAP_SYSTEM_INVENTORY = 1ULL << 16,
};

typedef enum {
    ESP_IRIS_TLV_DEVICE_ID = 0x01,
    ESP_IRIS_TLV_BOOT_ID = 0x02,
    ESP_IRIS_TLV_UPTIME_US = 0x03,
    ESP_IRIS_TLV_PROTOCOL_VERSION = 0x04,
    ESP_IRIS_TLV_CAPABILITIES = 0x05,
    ESP_IRIS_TLV_TRANSPORT = 0x06,
    ESP_IRIS_TLV_AUTH_MODE = 0x07,
    ESP_IRIS_TLV_RESET_REASON = 0x08,
    ESP_IRIS_TLV_PROJECT_NAME = 0x09,
    ESP_IRIS_TLV_APP_VERSION = 0x0a,
    ESP_IRIS_TLV_FIRMWARE_SHA256 = 0x0b,
    ESP_IRIS_TLV_IDF_VERSION = 0x0c,
    ESP_IRIS_TLV_MAX_PAYLOAD = 0x0d,
    ESP_IRIS_TLV_FREE_INTERNAL = 0x20,
    ESP_IRIS_TLV_MIN_FREE_INTERNAL = 0x21,
    ESP_IRIS_TLV_LOG_DROPPED = 0x22,
    ESP_IRIS_TLV_RX_FRAMES = 0x23,
    ESP_IRIS_TLV_TX_FRAMES = 0x24,
    ESP_IRIS_TLV_INVALID_FRAMES = 0x25,
    ESP_IRIS_TLV_LINK_COUNT = 0x26,
    ESP_IRIS_TLV_TASK_STACK_FREE_MIN = 0x27,
    ESP_IRIS_TLV_WORKER_ACTIVE_MAX_US = 0x28,
    ESP_IRIS_TLV_LIFECYCLE_STATE = 0x29,
    ESP_IRIS_TLV_INTERNAL_HEAP_USED = 0x2a,
    ESP_IRIS_TLV_STATIC_INTERNAL_BYTES = 0x2b,
    ESP_IRIS_TLV_PREVIOUS_BOOT_CRASH = 0x30,
    ESP_IRIS_TLV_CORE_DUMP_PRESENT = 0x31,
    ESP_IRIS_TLV_CORE_DUMP_VALID = 0x32,
    ESP_IRIS_TLV_CORE_DUMP_SIZE = 0x33,
    ESP_IRIS_TLV_CORE_DUMP_ELF_SHA256 = 0x34,
    ESP_IRIS_TLV_CORE_DUMP_ELF_SHA256_COMPLETE = 0x35,
    ESP_IRIS_TLV_PANIC_REASON = 0x36,
    ESP_IRIS_TLV_CORE_DUMP_CHUNK_MAX = 0x37,
    ESP_IRIS_TLV_AUTH_CHALLENGE = 0x40,
    ESP_IRIS_TLV_JOB_ID = 0x41,
    ESP_IRIS_TLV_JOB_STATE = 0x42,
    ESP_IRIS_TLV_JOB_PROGRESS = 0x43,
    ESP_IRIS_TLV_JOB_RESULT = 0x44,
    ESP_IRIS_TLV_MEDIA_DROPPED = 0x45,
    ESP_IRIS_TLV_OTA_PARTITION = 0x46,
} esp_iris_tlv_tag_t;

typedef struct {
    uint8_t channel;
    uint8_t type;
    uint16_t flags;
    uint32_t session_id;
    uint32_t request_id;
    uint32_t stream_id;
    uint32_t sequence;
    uint32_t payload_size;
} esp_iris_wire_header_t;

#ifdef __cplusplus
}
#endif
